### ISSUE TITLE
any ideas what I did wrong?

### ISSUE THREAD

**Issue by brumle80** [PaulSec/Shodan-mattermost#1]
Traceback (most recent call last):
File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
self.finish_request(request, client_address)
File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
self.handle()
File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
self.handle_one_request()
File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
method()
File "/opt/shodan-mattermost/mattershodan.py", line 73, in do_POST
responsetext = shodan_search_host(MattermostRequest.text)
AttributeError: type object 'MattermostRequest' has no attribute 'text'

**Comment by uhlhosting** [comment]
This needs to be upgraded to work with latest version of mattermost.
